### ISSUE TITLE
yaml-mode doesn't show any colors

### ISSUE THREAD

**Issue by rdeusser** [ianpan870102/tron-legacy-emacs-theme#9]
yaml-mode doesn't seem to have any sort of syntax highlighting.

![Screen Shot 2020-06-09 at 1 11 08 PM](https://user-images.githubusercontent.com/5935071/84178613-b3467200-aa52-11ea-8f96-398808ea165b.png)

Am I missing something?

**Comment by ianpan870102** [comment]
You're right, `yaml-mode` has not-so-ideal font lock supports, and doesn't expose their individual faces for us to customize (see [this issue](https://github.com/yoshiki/yaml-mode/issues/55)). In tron-legacy theme, the variable name face is currently set to be equal to the default foreground, that's why in your screenshot it all look the same. If you really want to show different colours in yaml buffers, you're best bet as of now is to customize tron-legacy's font-lock-variable-name-face.

Here's one example:

```emacs-lisp
(use-package tron-legacy-theme
  :custom-face
  (font-lock-variable-name-face ((t (:foreground "#8Fd4FF"))))
  :config
  (load-theme 'tron-legacy t))
```

And here's the result in `yaml-mode`:

![image](https://user-images.githubusercontent.com/36686900/84236956-16a3d300-ab2b-11ea-8ac0-2a00b8a16c0e.png)
